name: "Test"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  x86-64:
    runs-on: ubuntu-20.04
    steps:

    # Installation
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    # Build
    - name: Build
      run: |
        nix-build .
